project:
  type: website
  output-dir: docs
  
website:
  title: "Alex Yuan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - readings.qmd
      - writing.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



